name: CD Attendance-checker-logic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      #   - name: Make application.yml
      #     run: |
      #       cd ./src/main/resources
      #       touch ./application.yml
      #       echo "${{ secrets.PROPERTIES }}" > ./application.yml
      #     shell: bash
      - name: Show dir
        # run: |
        #   chmod +x gradlew
        #   ./gradlew clean build -x test
        run: ls -al
        shell: bash

      - name: Grant execute for gradlew
        # run: |
        #   chmod +x gradlew
        #   ./gradlew clean build -x test
        run: chmod +x gradlew
        shell: bash

      - name: Login to Docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t pks5294/attendance-check-logic .

      - name: Publish image to docker hub
        run: docker push pks5294/attendance-check-logic:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Docker hub
        run: docker pull pks5294/attendance-check-logic:latest

      - name: Delete Old Container
        run: docker rm -f attendance-check-logic-container

      - name: Run docker container
        run: docker run -d -p 9989:80 --name attendance-check-logic-container pks5294/attendance-check-logic:latest
